### PR TITLE
add Docker + :alias

### PR DESCRIPTION
**Pull request by r-cemper**

### CODE REVIEW

**Comment by isc-tleavitt** [comment]
Hi @r-cemper - nice to hear from you!

Can you elaborate on the intent of all of these changes? My first take is that some things in the PR may be appropriate for this package, and some are not. isc.json is very much a "building block" and is unlikely to be developed outside the context of another consuming package, for which the preferred development workflow would be package manager-aware embedded source control with multiple root directories (https://github.com/intersystems/git-source-control/issues can do this). Also, this project is ultimately downstream from an internal-to-InterSystems branch (though it still welcomes PRs on principle). That branch is our source of truth for module versioning, such that it's likely to be confusing for a bot to be bumping the version in GitHub specifically.

**Comment by isc-tleavitt** [comment]
I'm also on principle not a fan of every IPM-enabled repo requiring the same set of boilerplate stuff that will slowly (or quickly) become stale and outdated. There's got to be a better way to centralize the definition of that boilerplate and then parameterize to say "use the latest-and-greatest boilerplate with GitHub repo X which contains an IPM package"

**Comment by isc-tleavitt** [comment]
Putting this link here for my later reference thinking about the general problem: https://stackoverflow.com/a/66613287

**Comment by r-cemper** [comment]
Isolate Docker from main repo into [isc-json_docker](https://github.com/rcemper/isc-json_docker)

**Pull request closed without merging**
